Rename styles from edit to popup
omarcompany/prostogram-frontend pull request #5
Opened 2022-10-14 08:47 UTC by atatarov

We have a good styles which describe edit-popup. These styles can be used for other popup-components. So, let make these styles as a 'popup' and reuse for a new stuff.

2022-10-14 15:13 UTC, RostovtsevDanila approved these changes

2022-10-16 10:54 UTC, melodoc commented on src/components/main.tsx
> +        <div className="avatar" onClick={() => setIsEditAvatarPopupOpen(true)}>
лучше вынести в отдельный хендлер

2022-10-16 10:54 UTC, melodoc commented on src/components/main.tsx
> +            onClick={() => setIsEditProfilePopupOpen(true)}
И это тоже лучше вынести в отдельный хендлер

2022-10-16 10:56 UTC, melodoc commented on src/components/popups/popup-edit-avatar.tsx
> +  onClose: () => void;
если у нас один проп, его сигнатуру можно прописать прямо в функции PopupEditAvatar

2022-10-16 10:56 UTC, melodoc commented on src/components/popups/popup-edit-avatar.tsx
> +      children={<PopupLabel value={url} valueRef={avatarRef} />}
а почему valueRef?

2022-10-16 10:57 UTC, melodoc commented on src/components/popups/popup-edit-profile.tsx
> +      children={
children можно положить вот так

<Popup ...>
        <>
          <PopupLabel value={name} valueRef={nameRef} />
          <PopupLabel value={description} valueRef={descriptionRef} />
        </>
</Popup>

2022-10-16 10:59 UTC, melodoc commented on src/components/popups/popup-label.tsx
> +        id="description"
id у всех форм будет одинаковый, лучше id брать из пропа -> description_${value}

2022-10-16 11:00 UTC, melodoc commented on src/components/popups/popup.tsx
> +  const handleSubmit = onSubmit;
наверное, если ничего внутри кроме onSubmit не происходит, то можно в onClick передать его сразу

2022-10-16 11:01 UTC, melodoc requested changes
улучшения по комментариям

2022-10-16 21:36 UTC, melodoc approved these changes

2022-10-16 21:36 UTC, merged